IOWebApplication/Controllers/CaseGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using DataTables.AspNet.Core;
using IOWebApplication.Core.Contracts;
using IOWebApplication.Core.Helper;
using IOWebApplication.Core.Helper.GlobalConstants;
using IOWebApplication.Core.Models;
using IOWebApplication.Extensions;
using IOWebApplication.Infrastructure.Data.Models.Nomenclatures;
using IOWebApplication.Infrastructure.Models.ViewModels;
using IOWebApplication.Infrastructure.Models.ViewModels.Common;
using IOWebApplication.Infrastructure.Models.ViewModels.Nomenclatures;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
namespace IOWebApplication.Controllers
{
    public class CaseGroupController : GlobalAdminBaseController
    {
        private readonly ICaseGroupService service;
        private readonly INomenclatureService nomService;
        private readonly ICommonService commonService;

        public CaseGroupController(ICaseGroupService _service, INomenclatureService _nomService, ICommonService _commonService)
        {
            service = _service;
            nomService = _nomService;
            commonService = _commonService;
        }

        //основен вид дело
        public IActionResult Index()
        {

            return View();
        }

        /// <summary>
        /// Извличане на данни за основни видове дела
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult ListData(IDataTablesRequest request)
        {
            var data = service.CaseGroup_Select();

            return request.GetResponse(data);
        }

        /// <summary>
        /// Добавяне на основен вид дело
        /// </summary>
        /// <returns></returns>
        public IActionResult Add()
        {
            return View(nameof(Edit), new CaseGroup());
        }

        /// <summary>
        /// Редакция на на основен вид дело
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Edit(int id)
        {
            var model = service.GetById<CaseGroup>(id);
            return View(nameof(Edit), model);
        }

        /// <summary>
        /// Запис на на основен вид дело
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(CaseGroup model)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(Edit), model);
            }
            var currentId = model.Id;
            if (service.CaseGroup_SaveData(model))
            {
                this.SaveLogOperation(currentId == 0, model.Id);
                SetSuccessMessage(MessageConstant.Values.SaveOK);
                return RedirectToAction(nameof(Edit), new { id = model.Id });
            }
            else
            {
                SetErrorMessage(MessageConstant.Values.SaveFailed);
            }
            return View(nameof(Edit), model);
        }

        /// <summary>
        /// Промяна на подредбата на основен вид дело
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult ChangeOrder(ChangeOrderModel model)
        {
            var caseGroup = service.GetById<CaseGroup>(model.Id);
            Func<CaseGroup, int?> orderProp = x => x.OrderNumber;
            Expression<Func<CaseGroup, int?>> setterProp = (x) => x.OrderNumber;
            bool result = service.ChangeOrder(model.Id, model.Direction == "up", orderProp, setterProp, null);

            if (!result)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Проблем при смяна на реда");
            }

            return Ok();
        }

        //Точен вид дело
        public IActionResult CaseTypeList(int caseGroupId)
        {
            var casegroup = service.GetById<CaseGroup>(caseGroupId);
            ViewBag.caseGroupId = casegroup.Id;
            ViewBag.caseGrouplabel = casegroup.Label;
            ViewBag.breadcrumbs = new List<BreadcrumbsVM>()
            {
                new BreadcrumbsVM()
                {
                    Title = casegroup.Label,
                    Href = Url.Action("Index")
                }
            };
            return View();
        }

        /// <summary>
        /// Извличане на данни за точни видове дела
        /// </summary>
        /// <param name="request"></param>
        /// <param name="caseGroupId"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult ListDataCaseType(IDataTablesRequest request, int caseGroupId)
        {
            var data = service.CaseType_Select(caseGroupId);

            return request.GetResponse(data);
        }

        /// <summary>
        /// Добавяне на точен вид дело
        /// </summary>
        /// <param name="caseGroupId"></param>
        /// <returns></returns>
        public IActionResult AddCaseType(int caseGroupId)
        {
            SetViewbagCaseType();

            var model = new CaseType()
            {
                CaseGroupId = caseGroupId
            };
            return View(nameof(EditCaseType), model);
        }

        /// <summary>
        /// Редакция на Точен вид дело
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult EditCaseType(int id)
        {
            SetViewbagCaseType();
            var model = service.GetById<CaseType>(id);
            return View(nameof(EditCaseType), model);
        }

        /// <summary>
        /// Запис на Точен вид дело
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult EditCaseType(CaseType model)
        {
            SetViewbagCaseType();
            if (!ModelState.IsValid)
            {
                return View(nameof(EditCaseType), model);
            }
            var currentId = model.Id;
            if (service.CaseType_SaveData(model))
            {
                this.SaveLogOperation(currentId == 0, model.Id);
                SetSuccessMessage(MessageConstant.Values.SaveOK);
                return RedirectToAction(nameof(EditCaseType), new { id = model.Id });
            }
            else
            {
                SetErrorMessage(MessageConstant.Values.SaveFailed);
            }
            return View(nameof(EditCaseType), model);
        }

        /// <summary>
        /// Промяна на подредбата на точен вид дело
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult ChangeOrderCaseType(ChangeOrderModel model)
        {
            var caseType = service.GetById<CaseType>(model.Id);
            Func<CaseType, int?> orderProp = x => x.OrderNumber;
            Expression<Func<CaseType, int?>> setterProp = (x) => x.OrderNumber;
            Expression<Func<CaseType, bool>> predicate = x => x.CaseGroupId == caseType.CaseGroupId;
            bool result = service.ChangeOrder(model.Id, model.Direction == "up", orderProp, setterProp, predicate);

            if (!result)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Проблем при смяна на реда");
            }

            return Ok();
        }

        void SetViewbagCaseType()
        {
        }



        //Списък шифри
        public IActionResult CaseCodeList()
        {
            ViewBag.breadcrumbs = commonService.Breadcrumbs_CaseCode().DeleteOrDisableLast();

            ViewBag.filterCaseTypeId_ddl = nomService.GetDropDownList<CaseType>();
            ViewBag.filterCaseTypeId = -1;

            return View();
        }

        /// <summary>
        /// Извличане на данни за шифри
        /// </summary>
        /// <param name="request"></param>
        /// <param name="caseTypeId"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult ListDataCaseCode(IDataTablesRequest request, int caseTypeId)
        {
            var data = service.CaseCode_Select(caseTypeId);

            return request.GetResponse(data);
        }

        public void SetBreadcrumsCaseCode(int id)
        {
            if (id > 0)
                ViewBag.breadcrumbs = commonService.Breadcrumbs_CaseCodeEdit(id).DeleteOrDisableLast();
            else
                ViewBag.breadcrumbs = commonService.Breadcrumbs_CaseCodeAdd().DeleteOrDisableLast();
        }

        /// <summary>
        /// Добавяне на шифър
        /// </summary>
        /// <returns></returns>
        public IActionResult AddCaseCode()
        {
            SetBreadcrumsCaseCode(0);
            var model = new CaseCode()
            {
            };
            return View(nameof(EditCaseCode), model);
        }

        /// <summary>
        /// Редакция на шифър
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult EditCaseCode(int id)
        {
            SetBreadcrumsCaseCode(id);
            var model = service.GetById<CaseCode>(id);
            return View(nameof(EditCaseCode), model);
        }

        /// <summary>
        /// Запис на шифър
        /// </summary>
        /// <param name="model"></param>
        /// <param name="typesJson"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult EditCaseCode(CaseCode model, string typesJson)
        {
            if (!ModelState.IsValid)
            {
                SetBreadcrumsCaseCode(model.Id);
                return View(nameof(EditCaseCode), model);
            }
            var currentId = model.Id;
            List<int> codeTypes = JsonConvert.DeserializeObject<List<int>>(typesJson);

IOWebApplication/Views/CaseGroup/CaseCodeList.cshtml
@{
    int? filterCaseTypeId = ViewBag.filterCaseTypeId;
    ViewData["Title"] = "Списък Шифри ";
}
@model int?
@inject IViewLocalizer Localizer
@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}
<div class="row">
    <div class="col-md-12">
        @Html.EditorFor(model => filterCaseTypeId, "GenericDropDown")
    </div>
</div>

<div class="row">
    <div class="col-md-12 text-right pb-15">
        <a asp-action="AddCaseCode" class="btn btn-success">
            <i class="fa fa-plus"></i>
            Добави
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListDataCaseCode")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                        d.caseTypeId = $("#filterCaseTypeId").val();
                    }

                },
                columns: [
                    {
                        name: 'orderNumber',
                        data: 'orderNumber',
                        title: 'Номер по ред',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'code',
                        data: 'code',
                        title: 'Код',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'label',
                        data: 'label',
                        title: 'Етикет',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'lawBaseDescription',
                        data: 'lawBaseDescription',
                        title: 'Правно основание',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'isActive',
                        data: "isActive",
                        title: 'Активен',
                        sortable: true,
                        searchable: false,
                        className: "text-center",
                        "render": function (value) {
                            return value ? 'Да' : 'Не';
                        }
                    },
                    {
                        className: 'col-md-1',
                        name: 'dateStart',
                        data: 'dateStart',
                        title: 'Начална дата',
                        sortable: true,
                        searchable: false,
                        "render": function (value) {
                            if (value)
                                return moment(value).format("DD.MM.YYYY");
                            else
                                return "";
                        }
                    },
                    {
                        className: 'col-md-1',
                        name: 'dateEnd',
                        data: 'dateEnd',
                        title: 'Крайна дата',
                        sortable: true,
                        searchable: false,
                        "render": function (value) {
                            if (value)
                                return moment(value).format("DD.MM.YYYY");
                            else
                                return "";
                        }
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport col-md-1",
                        "render": function (value) {
                            return TemplateToHtml('#templateEdit', value);
                        }
                    }
                ]
            });

            $(document).on('click', '.orderButton', savePosition);

            function savePosition(e) {
                var element = e.currentTarget;
                var data = element.dataset;

                element.setAttribute("disabled", "");
                $.ajax({
                    method: "POST",
                    url: '@Url.Action("ChangeOrderCaseCode")',
                    dataType: "json",
                    data: data
                }).fail(function (jqXHR, status, message) {
                    if (jqXHR.responseText) {
                        //messageHelper.ShowErrorMessage(jqXHR.responseText);
                    }
                }).always(function () {
                    table.draw(false);
                });
            };
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <a href="#" data-id="{{this}}" data-direction="up" class="orderButton btn btn-info btn-sm" title="@Localizer[" btnUp"]"><i class="fa fa-angle-up"></i></a>
        <a href="#" data-id="{{this}}" data-direction="down" class="orderButton btn btn-primary btn-sm" title="@Localizer[" btnDown"]"><i class="fa fa-angle-down"></i></a>
        <a href="@Url.Action("EditCaseCode")/{{this}}" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
    </script>
}

<script>
    $("#filterCaseTypeId").change(function () {
        refreshTable('#mainTable');
    });
</script>

IOWebApplication/Views/CaseGroup/CaseTypeList.cshtml
@{
    var caseGroupId = ViewBag.caseGroupId;
    ViewData["Title"] = "Списък Точен вид дело към " + ViewBag.caseGrouplabel;
}
@inject IViewLocalizer Localizer
@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}

<div class="row">
    <div class="col-md-12 text-right pb-15">
        <a asp-action="AddCaseType" asp-route-caseGroupId="@caseGroupId" class="btn btn-success">
            <i class="fa fa-plus"></i>
            Добави
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

<div class="row">
    <div class="form-group col-md-12">
        <a asp-action="Index" class="btn btn-danger">Назад</a>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListDataCaseType")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                        d.caseGroupId = @caseGroupId;
                    }

                },
                columns: [
                    {
                        name: 'orderNumber',
                        data: 'orderNumber',
                        title: 'Номер по ред',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'label',
                        data: 'label',
                        title: 'Етикет',
                        sortable: true,
                        searchable: true
                    },                    
                    {
                        name: 'isActive',
                        data: "isActive",
                        title: 'Активен',
                        sortable: true,
                        searchable: false,
                        className: "text-center",
                        "render": function (value) {
                            return value ? 'Да' : 'Не';
                        }
                    },
                    {
                        className: 'col-md-1',
                        name: 'dateStart',
                        data: 'dateStart',
                        title: 'Начална дата',
                        sortable: true,
                        searchable: false,
                        "render": function (value) {
                            if (value)
                                return moment(value).format("DD.MM.YYYY");
                            else
                                return "";
                        }
                    },
                    {
                        className: 'col-md-1',
                        name: 'dateEnd',
                        data: 'dateEnd',
                        title: 'Крайна дата',
                        sortable: true,
                        searchable: false,
                        "render": function (value) {
                            if (value)
                                return moment(value).format("DD.MM.YYYY");
                            else
                                return "";
                        }
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#templateEdit', value);
                        }
                    }
                ]
            });

            $(document).on('click', '.orderButton', savePosition);

            function savePosition(e) {
                var element = e.currentTarget;
                var data = element.dataset;

                element.setAttribute("disabled", "");
                $.ajax({
                    method: "POST",
                    url: '@Url.Action("ChangeOrderCaseType")',
                    dataType: "json",
                    data: data
                }).fail(function (jqXHR, status, message) {
                    if (jqXHR.responseText) {
                        //messageHelper.ShowErrorMessage(jqXHR.responseText);
                    }
                }).always(function () {
                    table.draw(false);
                });
            };
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <a href="#" data-id="{{this}}" data-direction="up" class="orderButton btn btn-info btn-sm" title="@Localizer[" btnUp"]"><i class="fa fa-angle-up"></i></a>
        <a href="#" data-id="{{this}}" data-direction="down" class="orderButton btn btn-primary btn-sm" title="@Localizer[" btnDown"]"><i class="fa fa-angle-down"></i></a>
        <a href="@Url.Action("EditCaseType")/{{this}}" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"> Редакция</span></a>
        <a href="@Url.Action("IndexCaseTypeUnit")/{{this}}" class="btn btn-def btn-sm" title="Състави"><i class="fa fa-users"></i><span class="hidden-sm hidden-xs"> Състави</span></a>
    </script>
}

IOWebApplication/Views/CaseGroup/Edit.cshtml
@model CaseGroup
@using IOWebApplication.Infrastructure.Data.Models.Nomenclatures

@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Редакция";
    }
    else
    {
        ViewData["Title"] = "Добавяне";
    }

}

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            @Html.HiddenFor(x => x.Id)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="saveContainer">
                <partial name="_SaveFormContent" model="@("#saveContainer")" />
                <div class="row">
                    <div class="col-lg-3">@Html.EditorFor(x => x.Code)</div>
                    <div class="col-lg-9">@Html.EditorFor(x => x.Label)</div>
                </div>                
                @Html.EditorFor(x => x.Description)
                @Html.EditorFor(x => x.IsActive)

                @Html.EditorFor(x => x.DateStart)
                @Html.EditorFor(x => x.DateEnd)
            </div>

            <div class="form-group">
                <input type="submit" value="Запис" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-danger">Назад</a>
                @if (Model.Id > 0)
                {
                    <div class="pull-right">
                        @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = Model.Id.ToString() })
                    </div>
                }
            </div>
        </form>
    </div>
</div>

IOWebApplication/Views/CaseGroup/EditCaseType.cshtml
@model CaseType
@using IOWebApplication.Infrastructure.Data.Models.Nomenclatures

@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Редакция";
    }
    else
    {
        ViewData["Title"] = "Добавяне";
    }

}

<div class="row">
    <div class="col-md-6">
        <form asp-action="EditCaseType" method="post">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CaseGroupId)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="saveContainer">
                <partial name="_SaveFormContent" model="@("#saveContainer")" />
                @Html.EditorFor(x => x.Code)
                @Html.EditorFor(x => x.Label)
                @Html.EditorFor(x => x.Description)
                @Html.EditorFor(x => x.IsActive)

                @Html.EditorFor(x => x.DateStart)
                @Html.EditorFor(x => x.DateEnd)
            </div>

            <div class="form-group">
                <input type="submit" value="Запис" class="btn btn-success" />
                <a asp-action="CaseTypeList" asp-route-caseGroupId="@Model.CaseGroupId" class="btn btn-danger">Назад</a>
                @if (Model.Id > 0)
                {
                    <div class="pull-right">
                        @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = Model.Id.ToString() })
                    </div>
                }
            </div>
        </form>
    </div>
</div>

IOWebApplication/Views/CaseGroup/EditTypeUnit.cshtml
@model CaseTypeUnitEditVM
@using IOWebApplication.Infrastructure.Models.ViewModels.Nomenclatures

@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Редакция на състави по точен вид дело";
    }
    else
    {
        ViewData["Title"] = "Добавяне на състави по точен вид дело";
    }
}

@section breadcrumb{
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")" title="Начало"><i class="fa fa-home"></i></a></li>
    </ol>
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="EditTypeUnit" method="post">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CaseTypeId)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="saveContainer">
                <partial name="_SaveFormContent" model="@("#saveContainer")" />

                <fieldset class="is-fieldset">
                    <legend>Основни данни</legend>
                    <div class="row">
                        <div class="col-lg-6">@Html.EditorFor(x => x.Label)</div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">@Html.EditorFor(x => x.DateStart, "DateTime")</div>
                        <div class="col-lg-6">@Html.EditorFor(x => x.DateEnd, "DateTime")</div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12">@Html.EditorFor(x => x.Description, "Textarea")</div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">@Html.EditorFor(x => x.IsActive, "Boolean")</div>
                    </div>
                </fieldset>

                <fieldset class="is-fieldset">
                    <legend>Състав</legend>
                    <div class="row">
                        <div class="col-lg-12">@Html.EditorFor(x => x.CaseTypeUnitCounts)</div>
                    </div>
                </fieldset>
            </div>
            <div class="form-group">
                <input type="submit" value="Запис" class="btn btn-success" />
                <a asp-controller="CaseGroup" asp-action="IndexCaseTypeUnit" asp-route-id="@Model.CaseTypeId" class="btn btn-danger">Назад</a>
                @if (Model.Id > 0)
                {
                    <div class="pull-right">
                        @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = Model.Id.ToString() })
                    </div>
                }
            </div>
        </form>
    </div>
</div>

IOWebApplication/Views/CaseGroup/IndexCaseTypeUnit.cshtml
@using IOWebApplication.Infrastructure.Constants
@using IOWebApplication.Infrastructure.Models.ViewModels

@{
    var caseTypeId = ViewBag.caseTypeId;
    ViewData["Title"] = "Състави по точен вид дело " + ViewBag.CaseName;
}

@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}


<div class="row">
    <div class="col-md-12">
        <partial name="../CaseGroup/_CaseTypeUnit.cshtml" model="@caseTypeId" />
    </div>
</div>

IOWebApplication/Views/CaseGroup/_CaseTypeUnit.cshtml
@model int

<div class="row">
    <div class="col-md-12 text-right pb-15">
        <a asp-controller="CaseGroup" asp-action="AddTypeUnit" asp-route-caseTypeId="@Model" class="btn btn-success btn-sm">
            <i class="fa fa-plus"></i>
            Добави
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table id="caseTypeUnitMainTable" class="table table-hover table-striped"></table>
    </div>
</div>


<script>
        $(function () {
            var table = $('#caseTypeUnitMainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListDataTypeUnit", "CaseGroup")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                        d.caseTypeUnitId = @Model;
                    }

                },
                columns: [
                    {
                        name: 'label',
                        data: 'label',
                        title: 'Име',
                        sortable: true,
                        searchable: true
                    }
                    ,
                    {
                        name: 'actions',
                        data: null,
                        title: "Състав",
                        sortable: false,
                        searchable: false,
                        className: "text-left",
                        "render": function (a,b,item,d) {
                            return TemplateToHtml('#caseTypeUnitTemplateCounts', item);
                        }
                    },
                    {
                        name: 'dateStart',
                        data: 'dateStart',
                        title: 'Дата',
                        sortable: true,
                        searchable: true,
                        render: function (data) {
                            return moment(data).format("DD.MM.YYYY");
                        }
                    },
                    {
                        name: 'isActiveLabel',
                        data: 'isActiveLabel',
                        title: 'Активен',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#caseTypeUnitTemplateEdit', value);
                        }
                    }
                ]
            });


        });
</script>

<script id="caseTypeUnitTemplateEdit" type="text/x-handlebars-template">
    <a href="@Url.Action("EditTypeUnit", "CaseGroup")?id={{this}}" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
</script>
<script id="caseTypeUnitTemplateCounts" type="text/x-handlebars-template">
    {{#each counts}}
    {{label}}:
    <b>{{value}}</b>
    <br />
    {{/each}}
</script>