IOWebApplication/Controllers/AjaxController.cs
using DataTables.AspNet.Core;
using IO.LogOperation.Models;
using IO.LogOperation.Service;
using IOWebApplication.Core.Contracts;
using IOWebApplication.Extensions;
using IOWebApplication.Infrastructure.Constants;
using IOWebApplication.Infrastructure.Contracts;
using IOWebApplication.Infrastructure.Data.Models;
using IOWebApplication.Infrastructure.Data.Models.Cases;
using IOWebApplication.Infrastructure.Data.Models.Nomenclatures;
using IOWebApplication.Infrastructure.Extensions;
using IOWebApplication.Infrastructure.Models;
using IOWebApplication.Infrastructure.Models.ViewModels;
using IOWebApplication.Infrastructure.Models.ViewModels.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Encodings.Web;
using System.Threading;
using System.Web;

namespace IOWebApplication.Controllers
{
    [DisableAudit]
    [Authorize]
    public class AjaxController : Controller
    {
        private readonly INomenclatureService nomenclatureService;
        private readonly ICaseService caseService;
        private readonly IUserContext userContext;
        private readonly ICommonService commonService;
        private readonly ICasePersonService casePersonService;
        private readonly ICalendarService calendarService;
        private readonly ICaseGroupService caseGroupService;
        private readonly ICaseLoadIndexService caseLoadIndexService;
        private readonly ICdnService cdnService;

        protected readonly ILogOperationService<ApplicationDbContext> logOperation;

        public AjaxController(
            INomenclatureService _nomenclatureService,
            ICaseService _caseService,
            ICommonService _commonService,
            IUserContext _userContext,
            ICasePersonService _casePersonService,
            ICalendarService _calendarService,
            ICaseGroupService _caseGroupService,
            ICaseLoadIndexService _caseLoadIndexService,
            ILogOperationService<ApplicationDbContext> _logOperation,
            ICdnService _cdnService)
        {
            nomenclatureService = _nomenclatureService;
            caseService = _caseService;
            commonService = _commonService;
            userContext = _userContext;
            logOperation = _logOperation;
            calendarService = _calendarService;
            casePersonService = _casePersonService;
            caseGroupService = _caseGroupService;
            caseLoadIndexService = _caseLoadIndexService;
            cdnService = _cdnService;
        }

        [HttpGet]
        public IActionResult SearchEkatte(string query)
        {
            return new JsonResult(nomenclatureService.GetEkatte(query));
        }

        [HttpGet]
        public IActionResult SearchEkatteEispp(string query)
        {
            return new JsonResult(nomenclatureService.GetEkatteEispp(query));
        }

        [HttpGet]
        public IActionResult GetEkatte(string id)
        {
            var ekatte = nomenclatureService.GetEkatteById(id);

            if (ekatte == null)
            {
                return BadRequest();
            }

            return new JsonResult(ekatte);
        }

        [ResponseCache(Duration = 3600)]
        [AllowAnonymous]
        public IActionResult GetBlankFooter(int id, string date, string time)
        {
            var court = nomenclatureService.GetById<Infrastructure.Data.Models.Common.Court>(id);

            if (court != null)
            {
                var addData = "";
                if (!string.IsNullOrEmpty(court.PhoneNumber))
                {
                    addData += $";тел: {court.PhoneNumber.Trim()}";
                }
                if (!string.IsNullOrEmpty(court.Email))
                {
                    addData += $";email: {court.Email.Trim()}";
                }
                var _info = System.Net.WebUtility.HtmlEncode($"{court.Address}{addData}, {court.CityName}");
                return Content($"<!DOCTYPE html><html><head><meta http-equiv=Content-Type content=\"text/html;charset=utf-8\"></head><body style=\"width:80%;text-align:center;\">{_info}</body></html>", "text/html");
            }

            return Content("");
        }

        [HttpGet]
        public IActionResult SearchStreet(string ekatte, string query, int? streetType = null)
        {
            return new JsonResult(nomenclatureService.GetStreet(ekatte, query, streetType));
        }
        [HttpGet]
        public IActionResult GetStreet(string ekatte, string street_code)
        {
            var model = nomenclatureService.GetStreetByCode(ekatte, street_code);

            if (model == null)
            {
                return BadRequest();
            }

            return new JsonResult(model);
        }
        [HttpGet]
        public IActionResult GetEkatteByEisppCode(string eisppCode)
        {
            var model = nomenclatureService.GetEkatteByEisppCode(eisppCode);

            if (model == null)
            {
                return BadRequest();
            }

            return new JsonResult(model);
        }

        [HttpGet]
        public IActionResult GetEkatteByEisppCodeCategory(string eisppCode)
        {
            var model = nomenclatureService.GetEkatteByEisppCodeCategory(eisppCode);

            if (model == null)
            {
                return BadRequest();
            }

            return new JsonResult(model);
        }


        [HttpGet]
        public IActionResult FindPersonByUic(string uic, int uicType)
        {
            var model = commonService.Person_FindByUic(uic, uicType);

            return Json(model);
        }
        public IActionResult GetDDL_DocumentKind(int documentDirectionId, bool addDefaultElement = false)
        {
            return Json(nomenclatureService.GetDDL_DocumentKind(documentDirectionId, addDefaultElement));
        }
        public IActionResult GetDDL_DocumentGroup(int documentKindId)
        {
            return Json(nomenclatureService.GetDDL_DocumentGroup(documentKindId));
        }
        public IActionResult GetDDL_DocumentGroupByCourt(int documentKindId, int? courtOrganizationId = null)
        {
            //Thread.Sleep(2000);
            return Json(nomenclatureService.GetDDL_DocumentGroupByCourt(documentKindId, courtOrganizationId));
        }
        [HttpGet]
        public IActionResult GetDDL_DocumentType(int documentGroupId, bool addDefaultElement = false)
        {
            //Thread.Sleep(2000);
            var model = nomenclatureService.GetDDL_DocumentType(documentGroupId, addDefaultElement);

            return Json(model);
        }
        [HttpGet]
        public IActionResult GetDDL_DocumentTypeByCourt(int documentGroupId, bool addDefaultElement = false, int? courtOrganizationId = null)
        {
            var model = nomenclatureService.GetDDL_DocumentTypeByCourt(documentGroupId, addDefaultElement, false, courtOrganizationId);

            return Json(model);
        }
        [HttpGet]
        public IActionResult GetDDL_CaseType(int caseGroupId, bool addDefaultElement = true)
        {
            var model = nomenclatureService.GetDDL_CaseType(caseGroupId, addDefaultElement);

            return Json(model);
        }

        [HttpGet]
        public IActionResult GetDDL_CaseTypes(string caseGroupIds, bool addDefaultElement = false)
        {
            var model = nomenclatureService.GetDDL_CaseTypes(caseGroupIds, addDefaultElement);

            return Json(model);
        }

        [HttpGet]
        public IActionResult GetDDL_CaseTypeFromCourtType(int caseGroupId, string caseInstanceIds, bool addDefaultElement = true)
        {
            var model = nomenclatureService.GetDDL_CaseTypeFromCourtType(caseGroupId, caseInstanceIds, addDefaultElement);

            return Json(model);
        }

        [HttpGet]
        public IActionResult GetDDL_CaseTypeFromCourtTypeFirsLifecyclie(int caseGroupId, string caseInstanceIds, bool addDefaultElement = true)
        {
            var model = nomenclatureService.GetDDL_CaseTypeFromCourtType(caseGroupId, caseInstanceIds, addDefaultElement).Where(x => int.Parse(x.Value) != NomenclatureConstants.CaseTypes.VGD && int.Parse(x.Value) != NomenclatureConstants.CaseTypes.VChGD);

            return Json(model);
        }

        [HttpGet]
        public IActionResult Get_CaseTypeUnits(int caseTypeId)
        {
            var model = caseGroupService.CaseTypeUnit_Select(caseTypeId).ToList();

            var ddlUnits = model.Select(x => new LabelValueVM(x.Id, x.Label));

            return Json(ddlUnits.ToSelectList());
        }
        [HttpGet]
        public IActionResult Get_CaseTypeUnitsReserves(int caseTypeUnitId)
        {
            if (caseTypeUnitId == 0)
            {
                return null;
            }
            var model = caseGroupService.GetById_CaseTypeUnit(caseTypeUnitId);

            var ddlReserves = new List<LabelValueVM>();
            if (model.CaseTypeUnitCounts.Any(x => x.Id == NomenclatureConstants.JudgeRole.ReserveJudge && x.Value > 0))
            {
                ddlReserves.Add(new LabelValueVM(NomenclatureConstants.JudgeRole.ReserveJudge, $"С резервен съдия"));
            }
            if (model.CaseTypeUnitCounts.Any(x => x.Id == NomenclatureConstants.JudgeRole.ReserveJury && x.Value > 0))
            {
                ddlReserves.Add(new LabelValueVM(NomenclatureConstants.JudgeRole.ReserveJury, $"С резервен заседател"));
            }
            if (ddlReserves.Count() == 2)
            {
                ddlReserves.Insert(1, new LabelValueVM(NomenclatureConstants.JudgeRole.ReserveJudgeAndJury, $"С резервни съдия и заседател"));
            }
            if (ddlReserves.Any())
            {
                ddlReserves.Insert(0, new LabelValueVM(-1, $"Без резервни участници"));
            }

IOWebApplication/Views/CaseArchive/CaseArchive.cshtml
@using IOWebApplication.Infrastructure.Models.ViewModels.Case
@model CaseArchiveFilterVM

@{
    ViewData["Title"] = "Съдебни дела в архив";
}

@section breadcrumb{
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")" title="Начало"><i class="fa fa-home"></i></a></li>
        <li class="active">@ViewData["Title"]</li>
    </ol>
}

<div class="row">
    <div class="col-md-6 col-lg-2">
        @Html.EditorFor(m => m.DateFrom, "DateTime")
    </div>
    <div class="col-md-6 col-lg-2">
        @Html.EditorFor(m => m.DateTo, "DateTime")
    </div>
    <div class="col-md-6 col-lg-4">@Html.EditorFor(x => x.RegNumber)</div>
</div>
<div class="row">
    <div class="col-lg-3">@Html.EditorFor(m => m.IsDestroy, "Boolean")</div>
</div>

<div class="row">
    <div class="col-md-6 text-left pb-15">
        <button type="button" class="btn btn-primary" id="btnFilter" onclick="refreshTable('#mainTable');" value="Филтриране" title="Филтриране">
            Филтриране
            <i class="fa fa-search" title="Търсене"></i>
        </button>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListDataCaseArchive")",
                    "type": "POST",
                    "datatype": "json",
                    "data": function (d) {
                        d.model = {
                            DateFrom: $("#DateFrom").val(),
                            DateTo: $("#DateTo").val(),
                            RegNumber: $("#RegNumber").val(),
                            IsDestroy: $("#IsDestroy").is(":checked"),
                        };
                    }
                },
                columns: [
                    {
                        name: 'regDate',
                        data: 'regDate',
                        title: 'Дата архив',
                        sortable: true,
                        searchable: false,
                        render: function (data) {
                            return moment(data).format("DD.MM.YYYY");
                        }
                    },
                    {
                        name: 'regNumber',
                        data: 'regNumber',
                        title: 'Номер архив',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'caseTypeLabel',
                        data: 'caseTypeLabel',
                        title: 'Точен вид',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'caseRegDate',
                        data: 'caseRegDate',
                        title: 'Дата дело',
                        sortable: true,
                        searchable: false,
                        render: function (data) {
                            return moment(data).format("DD.MM.YYYY");
                        }
                    },
                    {
                        name: 'caseRegNumber',
                        data: 'caseRegNumber',
                        title: 'Пълен номер дело',
                        sortable: true,
                        searchable: true,
                        "render": function (a, b, item, d) {
                            return TemplateToHtml('#templateCase', item);
                        }
                    },
                    {
                        name: 'caseStateLabel',
                        data: 'caseStateLabel',
                        title: 'Статус',
                        sortable: true,
                        searchable: false
                    },
                    {
                        className: "text-right",
                        name: 'bookNumber',
                        data: 'bookNumber',
                        title: 'Номер на Том',
                        sortable: true,
                        searchable: false
                    },
                    {
                        className: "text-right",
                        name: 'bookYear',
                        data: 'bookYear',
                        title: 'Година на Том',
                        sortable: true,
                        searchable: false
                    },
                    {
                        className: "text-right",
                        name: 'storageYears',
                        data: 'storageYears',
                        title: 'Срок на съхранение години',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'dateDestroy',
                        data: 'dateDestroy',
                        title: 'Дата на унищожаване',
                        sortable: true,
                        searchable: false,
                        "render": function (value) {
                            if (value)
                                return moment(value).format("DD.MM.YYYY");
                            else
                                return "";
                        }
                    },
                    {
                        name: 'archiveLink',
                        data: 'archiveLink',
                        title: 'Архивна връзка',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        width:100,
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#templateEdit', value);
                        }
                    }
                ]
            });
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <div class="row">
            <a href="@Url.Action("Edit")?id={{this}}&&comeFrom=CaseArchive" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
        </div>
    </script>

    <script id="templateCase" type="text/x-handlebars-template">
        {{#if caseId}}
        <a href="@Url.Action("CasePreview","Case")/{{caseId}}" target="_blank" title="Преглед дело">{{caseRegNumber}}</a>
        {{/if}}
    </script>
}

IOWebApplication/Views/CaseArchive/CaseForArchive.cshtml
@using IOWebApplication.Infrastructure.Models.ViewModels.Case
@model CaseForArchiveFilterVM

@{
    ViewData["Title"] = "Съдебни дела за архивиране";
}

@section breadcrumb{
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")" title="Начало"><i class="fa fa-home"></i></a></li>
        <li class="active">@ViewData["Title"]</li>
    </ol>
}

<div class="row">
    <div class="col-lg-3">@Html.EditorFor(m => m.CaseGroupId, "GenericDropDown")</div>
    <div class="col-lg-3">@Html.EditorFor(m => m.CaseTypeId, "GenericDropDown")</div>
    <div class="col-lg-3">@Html.EditorFor(x => x.CaseNumber)</div>
</div>

<div class="row">
    <div class="col-md-6 text-left pb-15">
        <button type="button" class="btn btn-primary" id="btnFilter" onclick="refreshTable('#mainTable');" value="Филтриране" title="Филтриране">
            Филтриране
            <i class="fa fa-search" title="Търсене"></i>
        </button>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListDataCaseForArchive")",
                    "type": "POST",
                    "datatype": "json",
                    "data": function (d) {
                        d.model = {
                            CaseGroupId: $("#CaseGroupId").val(),
                            CaseTypeId: $("#CaseTypeId").val(),
                            CaseNumber: $("#CaseNumber").val(),
                        };
                    }
                },
                columns: [
                    {
                        name: 'caseTypeLabel',
                        data: 'caseTypeLabel',
                        title: 'Точен вид',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'regDate',
                        data: 'regDate',
                        title: 'Дата',
                        sortable: true,
                        searchable: true,
                        render: function (data) {
                            return moment(data).format("DD.MM.YYYY");
                        }
                    },
                    {
                        name: 'regNumber',
                        data: 'regNumber',
                        title: 'Пълен номер',
                        sortable: true,
                        searchable: true,
                        "render": function (a, b, item, d) {
                            return TemplateToHtml('#templateCase', item);
                        }
                    },
                    {
                        name: 'shortRegNumber',
                        data: 'shortRegNumber',
                        title: 'Кратък номер',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'caseCodeLabel',
                        data: 'caseCodeLabel',
                        title: 'Шифър',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'caseStateLabel',
                        data: 'caseStateLabel',
                        title: 'Статус',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        width:100,
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#templateEdit', value);
                        }
                    }
                ]
            });
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <div class="row">
            <a href="@Url.Action("Add")?caseId={{this}}" class="btn btn-warning btn-sm" title="Архивиране"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"> Архивиране</span></a>
        </div>
    </script>

    <script id="templateCase" type="text/x-handlebars-template">
        {{#if id}}
        <a href="@Url.Action("CasePreview","Case")/{{id}}" target="_blank" title="Преглед дело">{{regNumber}}</a>
        {{/if}}
    </script>

    <script>
        $(document).ready(function () {
            $('#CaseGroupId').trigger('change');
        });

        $('#CaseGroupId').change(function () {
            requestCombo('@Url.Action("GetDDL_CaseTypeFromCourtType", "Ajax")', { CaseGroupId: $(this).val() }, '#CaseTypeId', @Model.CaseTypeId);
        });
    </script>
}

IOWebApplication/Views/CaseArchive/CaseForDestroy.cshtml
@using IOWebApplication.Infrastructure.Models.ViewModels.Case
@model CaseForDestroyFilterVM

@{
    ViewData["Title"] = "Съдебни дела за унищожаване";
}

@section breadcrumb{
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")" title="Начало"><i class="fa fa-home"></i></a></li>
        <li class="active">@ViewData["Title"]</li>
    </ol>
}
<div class="row">
    <div class="col-md-6 col-lg-2">
        @Html.EditorFor(m => m.DateFrom, "DateTime")
    </div>
    <div class="col-md-6 col-lg-2">
        @Html.EditorFor(m => m.DateTo, "DateTime")
    </div>
    <div class="col-md-6 col-lg-4">@Html.EditorFor(x => x.CaseRegNumber)</div>
</div>

<div class="row">
    <div class="col-md-6 text-left pb-15">
        <button type="button" class="btn btn-primary" id="btnFilter" onclick="refreshTable('#mainTable');" value="Филтриране" title="Филтриране">
            Филтриране
            <i class="fa fa-search" title="Търсене"></i>
        </button>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListDataCaseForDestroy")",
                    "type": "POST",
                    "datatype": "json",
                    "data": function (d) {
                        d.model = {
                            DateFrom: $("#DateFrom").val(),
                            DateTo: $("#DateTo").val(),
                            CaseRegNumber: $("#CaseRegNumber").val(),
                        }
                    }
                },
                columns: [
                    {
                        name: 'regDate',
                        data: 'regDate',
                        title: 'Дата архив',
                        sortable: true,
                        searchable: false,
                        render: function (data) {
                            return moment(data).format("DD.MM.YYYY");
                        }
                    },
                    {
                        name: 'regNumber',
                        data: 'regNumber',
                        title: 'Номер архив',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'caseTypeLabel',
                        data: 'caseTypeLabel',
                        title: 'Точен вид',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'caseRegDate',
                        data: 'caseRegDate',
                        title: 'Дата дело',
                        sortable: true,
                        searchable: false,
                        render: function (data) {
                            return moment(data).format("DD.MM.YYYY");
                        }
                    },
                    {
                        name: 'caseRegNumber',
                        data: 'caseRegNumber',
                        title: 'Пълен номер дело',
                        sortable: true,
                        searchable: true,
                        "render": function (a, b, item, d) {
                            return TemplateToHtml('#templateCase', item);
                        }
                    },
                    {
                        name: 'caseStateLabel',
                        data: 'caseStateLabel',
                        title: 'Статус',
                        sortable: true,
                        searchable: false
                    },
                    {
                        className: "text-right",
                        name: 'storageYears',
                        data: 'storageYears',
                        title: 'Срок на съхранение години',
                        sortable: true,
                        searchable: false
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        width:100,
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#templateEdit', value);
                        }
                    }
                ]
            });
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <div class="row">
            <a href="@Url.Action("Edit")?id={{this}}&comeFrom=CaseForDestroy" class="btn btn-warning btn-sm" title="Унищожаване"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
        </div>
    </script>
    <script id="templateCase" type="text/x-handlebars-template">
        {{#if caseId}}
        <a href="@Url.Action("CasePreview","Case")/{{caseId}}" target="_blank" title="Преглед дело">{{caseRegNumber}}</a>
        {{/if}}
    </script>

}