IOWebApplication/Controllers/CaseController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DataTables.AspNet.Core;
using IOWebApplication.Core.Contracts;
using IOWebApplication.Core.Helper;
using IOWebApplication.Core.Helper.GlobalConstants;
using IOWebApplication.Extensions;
using IOWebApplication.Infrastructure.Constants;
using IOWebApplication.Infrastructure.Data.Models.Cases;
using IOWebApplication.Infrastructure.Data.Models.Documents;
using IOWebApplication.Infrastructure.Data.Models.Nomenclatures;
using IOWebApplication.Infrastructure.Extensions;
using IOWebApplication.Infrastructure.Models.ViewModels;
using IOWebApplication.Infrastructure.Models.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Rotativa.Extensions;

namespace IOWebApplication.Controllers
{
    public class CaseController : BaseController
    {
        private readonly ICaseService service;
        private readonly INomenclatureService nomService;
        private readonly ICommonService commonService;
        private readonly ICaseClassificationService classficationService;
        private readonly ICaseSelectionProtokolService caseSelectProtokolService;
        private readonly ICourtDepartmentService courtDepartmentService;
        private readonly IDocumentResolutionService docResolutionService;

        public CaseController(
            ICaseService _service,
            INomenclatureService _nomService,
            ICommonService _commonService,
            ICaseClassificationService _classficationService,
            ICaseSelectionProtokolService _caseSelectProtokolService,
            ICourtDepartmentService _courtDepartmentService,
            IDocumentResolutionService _docResolutionService)
        {
            service = _service;
            nomService = _nomService;
            commonService = _commonService;
            classficationService = _classficationService;
            caseSelectProtokolService = _caseSelectProtokolService;
            courtDepartmentService = _courtDepartmentService;
            docResolutionService = _docResolutionService;
        }

        /// <summary>
        /// Страница за дела по критерии от филтър
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            if (!CheckAccess(service, SourceTypeSelectVM.Case, null, AuditConstants.Operations.View))
            {
                return RedirectToAction(nameof(HomeController.AccessDenied), HomeController.ControlerName);
            }
            CaseFilter filter = new CaseFilter()
            {
                CaseYear = DateTime.Now.Year
            };
            SetViewbagIndex();
            SetHelpFile(HelpFileValues.CaseIndex);
            return View(filter);
        }

        /// <summary>
        /// Дела с непълен състав
        /// </summary>
        /// <returns></returns>
        public IActionResult CaseForSelection()
        {
            CaseFilter filter = new CaseFilter();
            SetViewbagIndex();
            SetHelpFile(HelpFileValues.IncompleteConstitutionInfo);
            return View(filter);
        }

        /// <summary>
        /// Извличане на информация за дела по филтър
        /// </summary>
        /// <param name="request"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult ListData(IDataTablesRequest request, CaseFilter model)
        {
            var data = service.Case_Select(userContext.CourtId, model);
            return request.GetResponse(data);
        }

        /// <summary>
        /// Извличане на информация за дела с непълен състав
        /// </summary>
        /// <param name="request"></param>
        /// <param name="model"></param>
        /// <returns></returns> 
        [HttpPost]
        public IActionResult ListDataForSelection(IDataTablesRequest request, CaseFilter model)
        {
            var data = service.Case_SelectForSelection(userContext.CourtId, model);
            return request.GetResponse(data);
        }

        /// <summary>
        /// Редакция на дело
        /// </summary>
        /// <param name="id"></param>
        /// <param name="taskid"></param>
        /// <returns></returns>
        public IActionResult Edit(int id, long? taskid = null)
        {
            var model = service.Case_SelectForEdit(id);
            if (model == null)
            {
                return Redirect_Denied("Търсения от Вас ресурс е невалиден или недостъпен в момента.");
            }
            if (!string.IsNullOrEmpty(model.RegNumber))
            {
                if (!CheckAccess(service, SourceTypeSelectVM.Case, id, AuditConstants.Operations.Update))
                {
                    return Redirect_Denied();
                }
            }
            else
            {
                if (!CheckAccess(service, SourceTypeSelectVM.Case, id, AuditConstants.Operations.View))
                {
                    return Redirect_Denied();
                }

                var document = service.GetById<Document>(model.DocumentId);
                if (document.IsOldNumber == true)
                {
                    model.IsOldNumber = true;
                }
                model.Description = document.Description;
            }

            int newCaseStateId = NomenclatureConstants.CaseState.New;
            if(taskid > 0)
            {
                var _task= service.GetById<Infrastructure.Data.Models.Common.WorkTask>(taskid);
                if(_task != null && _task.TaskTypeId == WorkTaskConstants.Types.Case_ForReject)
                {
                    newCaseStateId = NomenclatureConstants.CaseState.Rejected;
                }
            }

            //Ако не е образувано делото (чернова) - се предлага по подразбиране Образувано
            if (model.CaseStateId == NomenclatureConstants.CaseState.Draft && string.IsNullOrEmpty(model.RegNumber))
            {
                model.CaseStateId = newCaseStateId;
            }

            SetViewBagEdit(model);
            return View(nameof(Edit), model);
        }

        /// <summary>
        /// Запис на дело
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(CaseEditVM model)
        {
            SetViewBagEdit(model);

            ValidateCaseEdit(model);
            if (!ModelState.IsValid)
            {
                return View(nameof(Edit), model);
            }

            var currentId = model.Id;
            var isInsert = string.IsNullOrEmpty(model.RegNumber);
            if (service.Case_SaveData(model))
            {
                if (isInsert && !string.IsNullOrEmpty(model.RegNumber))
                {
                    CheckAccess(service, SourceTypeSelectVM.Case, model.Id, AuditConstants.Operations.Init);
                }
                else
                {
                    SetAuditContext(service, SourceTypeSelectVM.Case, model.Id, currentId == 0);
                }
                this.SaveLogOperation(isInsert, model.Id);
                SetSuccessMessage(MessageConstant.Values.SaveOK);
                if (isInsert)
                {
                    return RedirectToAction(nameof(Edit), new { id = model.Id });
                }
                else
                {
                    return RedirectToAction(nameof(CasePreview), new { id = model.Id });
                }
            }
            else
            {
                SetErrorMessage(MessageConstant.Values.SaveFailed);
            }
            return View(nameof(Edit), model);
        }

        /// <summary>
        /// Валидация преди запис
        /// </summary>
        /// <param name="model"></param>
        private void ValidateCaseEdit(CaseEditVM model)
        {
            if (model.IsOldNumber == true && model.OldDate.HasValue)
            {
                var caseGroup = nomService.GetById<CaseType>(model.CaseTypeId);
                if (!service.CheckCaseOldNumber(caseGroup.CaseGroupId, model.OldNumber, model.OldDate.Value))
                {
                    ModelState.AddModelError("OldNumber", $"Вече съществува дело с номер {model.OldNumber} от дата {model.OldDate:dd.MM.yyyy}");
                }
            }

            if (NomenclatureConstants.CaseState.UnregisteredManageble.Contains(model.CaseStateId))
            {
                //Ако делото е отказано от образуване - следните полета не са задължителни:
                model.CaseCodeId = 0;
                model.CourtGroupId = null;
                model.LoadGroupLinkId = null;
                model.CaseTypeUnitId = null;
                model.ProcessPriorityId = null;

                if (string.IsNullOrEmpty(model.CaseStateDescription))
                {
                    ModelState.AddModelError("CaseStateDescription", $"Полето 'Основание' е задължително при отказ от образуване.");
                }
            }
            else
            {
                if (model.CaseTypeId <= 0)
                    ModelState.AddModelError("CaseTypeId", $"Изберете 'Точен вид дело'.");

                if (model.CaseCharacterId <= 0)
                    ModelState.AddModelError("CaseCharacterId", $"Изберете 'Характер на дело'.");

                if (model.CaseCodeId <= 0)
                {
                    ModelState.AddModelError("CaseCodeId", $"Изберете 'Шифър'.");
                }

                if ((model.CourtGroupId ?? 0) <= 0)
                    ModelState.AddModelError("CourtGroupId", $"Изберете 'Съдебна група за разпределяне'.");

                if (model.CourtTypeId != NomenclatureConstants.CourtType.VKS && (model.LoadGroupLinkId ?? 0) <= 0)
                    ModelState.AddModelError("LoadGroupLinkId", $"Изберете 'Група по натовареност'.");

                if ((model.CaseTypeUnitId ?? 0) <= 0)

IOWebApplication/Controllers/CaseMoneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataTables.AspNet.Core;
using IOWebApplication.Core.Contracts;
using IOWebApplication.Core.Helper.GlobalConstants;
using IOWebApplication.Extensions;
using IOWebApplication.Infrastructure.Data.Models.Cases;
using IOWebApplication.Infrastructure.Data.Models.Nomenclatures;
using Microsoft.AspNetCore.Mvc;

namespace IOWebApplication.Controllers
{
    public class CaseMoneyController : BaseController
    {
        private readonly ICaseMoneyService service;
        private readonly INomenclatureService nomService;
        private readonly ICaseLawUnitService caseLawUnitService;
        private readonly ICaseSessionService sessionService;

        public CaseMoneyController(ICaseMoneyService _service, INomenclatureService _nomService, ICaseLawUnitService _caseLawUnitService,
            ICaseSessionService _sessionService)
        {
            service = _service;
            nomService = _nomService;
            caseLawUnitService = _caseLawUnitService;
            sessionService = _sessionService;
        }

        public IActionResult Index(int id, int? caseSessionId)
        {
            var tcase = service.GetById<Case>(id);
            ViewBag.caseId = id;
            ViewBag.caseSessionId = caseSessionId;
            ViewBag.casenumber = tcase.EISSPNumber;

            return View();
        }

        [HttpPost]
        public IActionResult ListData(IDataTablesRequest request, int caseId, int? caseSessionId)
        {
            var data = service.CaseMoney_Select(caseId, caseSessionId);

            return request.GetResponse(data);
        }

        public IActionResult Add(int caseId, int? caseSessionId)
        {
            SetViewbag(caseId, caseSessionId);
            var model = new CaseMoney()
            {
                CaseId = caseId,
                CourtId = userContext.CourtId,
                CaseSessionId = caseSessionId
            };
            return View(nameof(Edit), model);
        }

        public IActionResult Edit(int id)
        {
            var model = service.GetById<CaseMoney>(id);
            SetViewbag(model.CaseId, model.CaseSessionId);
            return View(nameof(Edit), model);
        }

        [HttpPost]
        public IActionResult Edit(CaseMoney model)
        {
            SetViewbag(model.CaseId, model.CaseSessionId);
            if (!ModelState.IsValid)
            {
                return View(nameof(Edit), model);
            }
            var currentId = model.Id;
            if (service.CaseMoney_SaveData(model))
            {
                this.SaveLogOperation(currentId == 0, model.Id);
                SetSuccessMessage(MessageConstant.Values.SaveOK);
                return RedirectToAction(nameof(Edit), new { id = model.Id });
            }
            else
            {
                SetErrorMessage(MessageConstant.Values.SaveFailed);
            }
            return View(nameof(Edit), model);
        }

        void SetViewbag(int caseId, int? caseSessionId)
        {
            ViewBag.MoneyTypeId_ddl = nomService.GetDropDownList<MoneyType>();
            ViewBag.CaseLawUnitId_ddl = caseLawUnitService.CaseLawUnit_SelectForDropDownList(caseId, null);
            ViewBag.RegNumber = service.GetById<Case>(caseId).RegNumber;

            if (caseSessionId != null)
            {
                var caseSession = sessionService.CaseSessionById(caseSessionId ?? 0);
                ViewBag.CaseSessionName = caseSession.SessionType?.Label + "/" + caseSession.DateFrom.ToString("dd.MM.yyyy");
            }
        }

    }
}

IOWebApplication/Views/CaseMoney/Edit.cshtml
@model CaseMoney
@using IOWebApplication.Infrastructure.Data.Models.Cases

@{
    IAccessControl access = (IAccessControl)ViewBag.AccessControl;

    if (Model.Id > 0)
    {
        ViewData["Title"] = access.CanChange ? "Редакция" : "Преглед";
    }
    else
    {
        ViewData["Title"] = "Добавяне";
    }
}

@section breadcrumb{
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")" title="Начало"><i class="fa fa-home"></i></a></li>
        <li><a href="@Url.Action("Index","Case")">Съдебни дела</a></li>
        <li><a href="@Url.Action("CasePreview","Case", new { id = Model.CaseId})">Дело @ViewBag.RegNumber</a></li>
        @if (Model.CaseSessionId != null)
        {
            <li><a href="@Url.Action("Preview", "CaseSession", new { id = Model.CaseSessionId })">@ViewBag.CaseSessionName</a></li>
        }
        <li class="active">@ViewData["Title"]</li>
    </ol>
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CaseId)
            @Html.HiddenFor(x => x.CourtId)
            @Html.HiddenFor(x => x.CaseSessionId)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="saveContainer">
                <partial name="_SaveFormContent" model="@("#saveContainer")" />
                @Html.EditorFor(x => x.CaseLawUnitId, "GenericDropDown")
                @Html.EditorFor(x => x.MoneyTypeId, "GenericDropDown")
                @Html.EditorFor(x => x.Amount)
                @Html.EditorFor(x => x.PaidDate)
                @Html.EditorFor(x => x.Description, "Textarea")
            </div>

            <div class="form-group">
                @if (access.CanChange)
                {
                    <input type="submit" value="Запис" class="btn btn-success" />
                }
                @if (Model.CaseSessionId == null)
                {
                    <a asp-controller="Case" asp-action="CasePreview" asp-route-id="@Model.CaseId" class="btn btn-danger">Назад</a>
                }
                else
                {
                    <a asp-controller="CaseSession" asp-action="Preview" asp-route-id="@Model.CaseSessionId" class="btn btn-danger">Назад</a>
                }
                @if (Model.Id > 0)
                {
                    <div class="pull-right">
                        @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = Model.Id.ToString() })
                    </div>
                }
            </div>
        </form>
    </div>
</div>

IOWebApplication/Views/CaseMoney/Index.cshtml
@using IOWebApplication.Infrastructure.Constants
@using IOWebApplication.Infrastructure.Models.ViewModels

@{
    var caseId = ViewBag.caseId;
    var caseSessionId = ViewBag.caseSessionId;
    if (caseSessionId == null)
    {
        ViewData["Title"] = "Суми по дело " + ViewBag.casenumber;
    }
    else
    {
        ViewData["Title"] = "Суми за заседание по дело " + ViewBag.casenumber;
    }
}

<div class="row">
    <div class="col-md-12">
        <partial name="../CaseMoney/_CaseMoney.cshtml" model="@new CaseMainDataVM { Id = caseId, CaseSessionId = caseSessionId} " />
    </div>
</div>

<div class="row">
    <div class="form-group row col-md-12">
        @if (caseSessionId == null)
        {
            <a asp-controller="Case" asp-action="CasePreview" asp-route-id="@caseId" class="btn btn-danger">Назад</a>
        }
        else
        {
            <a asp-controller="CaseSession" asp-action="Preview" asp-route-id="@caseSessionId" class="btn btn-danger">Назад</a>
        }
    </div>
</div>

IOWebApplication/Views/CaseMoney/_CaseMoney.cshtml
@model CaseMainDataVM
@using IOWebApplication.Infrastructure.Models.ViewModels
@inject IViewLocalizer Localizer

@{
    IAccessControl access = (IAccessControl)ViewBag.AccessControl;
}

@if (access.CanChange)
{
    <div class="row">
        <div class="col-md-12 text-right pb-15">
            <a asp-controller="CaseMoney" asp-action="Add" asp-route-caseId="@Model.Id" asp-route-caseSessionId="@Model.CaseSessionId" class="btn btn-success btn-sm">
                <i class="fa fa-plus"></i>
                Добави
            </a>
        </div>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <table id="caseMoneyMainTable" class="table table-hover table-striped"></table>
    </div>
</div>


<script>
        $(function () {
            var table = $('#caseMoneyMainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("ListData", "CaseMoney")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                        d.caseId = @Model.Id;
                        d.caseSessionId = @(Model.CaseSessionId??0);
                    }

                },
                columns: [
                    {
                        name: 'caseLawUnitName',
                        data: 'caseLawUnitName',
                        title: 'Участник',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'moneyTypeName',
                        data: 'moneyTypeName',
                        title: 'Вид сума',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'moneySignName',
                        data: 'moneySignName',
                        title: 'Тип',
                        sortable: true,
                        searchable: true
                    },
                    {
                        className: "text-right",
                        name: 'amount',
                        data: 'amount',
                        title: 'Сума',
                        sortable: true,
                        searchable: true,
                        "render": function (value) {
                            if (value)
                                return parseFloat(value).toFixed(2);
                            else
                                return "0.00";
                        }
                    },
                    {
                        className: 'col-md-1',
                        name: 'paidDate',
                        data: 'paidDate',
                        title: 'Платено на',
                        sortable: true,
                        searchable: false,
                        "render": function (value) {
                            if (value)
                                return moment(value).format("DD.MM.YYYY");
                            else
                                return "";
                        }
                    },
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#caseMoneyTemplateEdit', value);
                        }
                    }
                ]
            });
        });
</script>

<script id="caseMoneyTemplateEdit" type="text/x-handlebars-template">
    @if (access.CanChange)
    {
        <a href="@Url.Action("Edit", "CaseMoney")?id={{this}}" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
    }
    else
    {
        <a href="@Url.Action("Edit", "CaseMoney")?id={{this}}" class="btn btn-def btn-sm" title="Преглед"><i class="fa fa-eye"></i><span class="hidden-sm hidden-xs"></span></a>
    }
</script>