IOWebApplication/Controllers/EpepController.cs
using DataTables.AspNet.Core;
using Integration.Epep;
using IOWebApplication.Core.Contracts;
using IOWebApplication.Core.Helper.GlobalConstants;
using IOWebApplication.Extensions;
using IOWebApplication.Infrastructure.Constants;
using IOWebApplication.Infrastructure.Contracts;
using IOWebApplication.Infrastructure.Data.Models.Common;
using IOWebApplication.Infrastructure.Data.Models.Nomenclatures;
using IOWebApplication.Infrastructure.Extensions;
using IOWebApplication.Infrastructure.Models.ViewModels.Common;
using IOWebApplication.Infrastructure.Models.ViewModels.Epep;
using IOWebApplicationService.Infrastructure.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Threading.Tasks;

namespace IOWebApplication.Controllers
{

    public class EpepController : BaseController
    {
        private readonly IEpepConnectionService connector;
        private IeCaseServiceClient epepClient;
        private readonly IMQEpepService service;
        private readonly INomenclatureService nomService;
        private readonly ICasePersonService casePersonService;

        public EpepController(
            IEpepConnectionService _connector,
            IMQEpepService _service,
            INomenclatureService _nomService,
            ICasePersonService _casePersonService
            )
        {
            connector = _connector;
            service = _service;
            nomService = _nomService;
            casePersonService = _casePersonService;
        }

        //[AllowAnonymous]
        //public async Task<IActionResult> GetUserRegistration(string id)
        //{
        //    epepClient = await connector.Connect();
        //    return Json(await epepClient.GetUserRegistrationInfoByUsernameAsync(id));
        //}

        //[AllowAnonymous]
        //public async Task<IActionResult> GetPersonRegistrationById(string id)
        //{
        //    epepClient = await connector.Connect();
        //    return Json(await epepClient.GetPersonRegistrationByIdAsync(Guid.Parse(id)));
        //}

        //[AllowAnonymous]
        //public async Task<IActionResult> getcaseinfo(string id)
        //{
        //    epepClient = await connector.Connect();
        //    try
        //    {
        //        return Json(epepClient.GetSideIdentifiersByCaseId(Guid.Parse(id)));
        //    }catch(Exception ex)
        //    {
        //        return null;
        //    }
        //}

        //[AllowAnonymous]
        //public async Task<IActionResult> recoverdata()
        //{
        //    // epepClient = await connector.Connect();
        //    return Content(service.RecoverData(null));
        //}

        public IActionResult SendActPreparators(int id)
        {
            service.SendActPreparators(id);
            return Content("Заявката за актуализиране на участници по акта е добавена успешно.");
        }

        public IActionResult EpepUser()
        {
            SetHelpFile(HelpFileValues.Nom7);
            ViewBag.EpepUserTypeId_ddl = nomService.GetDropDownList<EpepUserType>();
            return View();
        }
        [HttpPost]
        public IActionResult EpepUser_ListData(IDataTablesRequest request, EpepUserFilterVM filter)
        {
            var data = service.EpepUser_Select(filter);
            return request.GetResponse(data);
        }

        public IActionResult EpepUser_Add(long? documentId = null)
        {
            var model = service.EpepUser_InitFromDocument(documentId);

            SetViewBag_EpepUser(model);
            return View(nameof(EpepUser_Edit), model);
        }
        public async Task<IActionResult> EpepUser_AddFromEmail(string email)
        {
            var model = await EpepUser_LoadDataByEmail(email);
            SetViewBag_EpepUser(model);
            return View(nameof(EpepUser_Edit), model);
        }
        public IActionResult EpepUser_Edit(int id)
        {
            var model = service.GetById<EpepUser>(id);
            SetViewBag_EpepUser(model);
            return View(nameof(EpepUser_Edit), model);
        }
        [HttpPost]
        public async Task<IActionResult> EpepUser_Edit(EpepUser model)
        {
            var error = service.EpepUser_Validate(model);
            if (!string.IsNullOrEmpty(error))
            {
                ModelState.AddModelError("", error);
            }
            if (model.Id == 0)
            {
                await Epep_Validation(model);
            }
            if (!ModelState.IsValid)
            {
                SetViewBag_EpepUser(model);
                return View(nameof(EpepUser_Edit), model);
            }
            int currentId = model.Id;
            if (service.EpepUser_SaveData(model))
            {
                SaveLogOperation(currentId == 0, model.Id);
                SetSuccessMessage(MessageConstant.Values.SaveOK);
                return RedirectToAction(nameof(EpepUser_Edit), new { id = model.Id });
            }
            else
            {
                SetSuccessMessage(MessageConstant.Values.SaveFailed);
                SetViewBag_EpepUser(model);
                return View(nameof(EpepUser_Edit), model);
            }
        }
        private async Task Epep_Validation(EpepUser model)
        {
            try
            {
                epepClient = await connector.Connect();
                var regInfo = await epepClient.GetUserRegistrationInfoByUsernameAsync(model.Email.ToLower());
                if (regInfo.IsRegistered)
                {
                    if (!regInfo.LawyerRegistrationId.IsEmpty())
                    {
                        if (model.EpepUserTypeId == EpepConstants.UserTypes.Lawyer)
                        {
                            return;
                        }
                        ModelState.AddModelError("", "Съществува създаден потребител на адвокат в ЕПЕП с тази електронна поща.");
                    }
                    if (!regInfo.PersonRegistrationId.IsEmpty())
                    {
                        if (model.EpepUserTypeId == EpepConstants.UserTypes.Person)
                        {
                            return;
                        }
                        ModelState.AddModelError("", "Съществува създаден потребител на частно лице в ЕПЕП с тази електронна поща.");
                    }
                    ViewBag.hasEpepUserOtherType = true;
                }
            }
            catch (Exception ex)
            {

            }
            finally
            {
                if (epepClient != null && epepClient.State == CommunicationState.Opened)
                {
                    await epepClient.CloseAsync();
                }
            }
        }

        private async Task<EpepUser> EpepUser_LoadDataByEmail(string email)
        {
            EpepUser model = new EpepUser();
            try
            {
                epepClient = await connector.Connect();
                var regInfo = await epepClient.GetUserRegistrationInfoByUsernameAsync(email.ToLower());
                if (regInfo.IsRegistered)
                {
                    if (!regInfo.LawyerRegistrationId.IsEmpty())
                    {
                        var epepLawyer = await epepClient.GetLawyerRegistrationByIdAsync(regInfo.LawyerRegistrationId.Value);
                        if (epepLawyer != null)
                        {
                            model.EpepUserTypeId = EpepConstants.UserTypes.Lawyer;
                            model.BirthDate = epepLawyer.BirthDate;
                            model.Email = epepLawyer.Email;
                            var lawyers = await epepClient.GetAllLawyersAsync();
                            var regLawyer = lawyers.Where(x => x.LawyerId == epepLawyer.LawyerId).FirstOrDefault();
                            if (regLawyer != null)
                            {
                                model.LawyerNumber = regLawyer.Number;

                                var lawunit = service.GetLawyerByNumber(model.LawyerNumber);
                                if (lawunit != null)
                                {
                                    model.LawyerLawUnitId = lawunit.Id;
                                    model.FullName = lawunit.FullName;
                                }
                                else
                                {
                                    ModelState.AddModelError(nameof(model.LawyerLawUnitId), $"Ненамерен адвокат {regLawyer.Name} с номер {regLawyer.Number}.");
                                }
                            }
                        }
                    }
                    if (!regInfo.PersonRegistrationId.IsEmpty())
                    {
                        var epepPerson = await epepClient.GetPersonRegistrationByIdAsync(regInfo.PersonRegistrationId.Value);
                        if (epepPerson != null)
                        {
                            model.EpepUserTypeId = EpepConstants.UserTypes.Person;
                            model.Uic = epepPerson.EGN;
                            model.FullName = epepPerson.Name;
                            model.BirthDate = epepPerson.BirthDate;
                            model.Address = epepPerson.Address;
                        }
                    }
                }

            }
            catch (Exception ex) { }
            finally
            {
                if (epepClient != null && epepClient.State == CommunicationState.Opened)
                {
                    await epepClient.CloseAsync();
                }
            }
            return model;
        }

        private void SetViewBag_EpepUser(EpepUser model)
        {
            ViewBag.EpepUserTypeId_ddl = nomService.GetDropDownList<EpepUserType>();

IOWebApplication/Views/Epep/EpepUser.cshtml
@{
    ViewData["Title"] = "ЕПЕП - Потребители";
}
@model IOWebApplication.Infrastructure.Models.ViewModels.Epep.EpepUserFilterVM
@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}
<div class="row">
    <div class="col-lg-3">@Html.EditorFor(m => m.EpepUserTypeId, "GenericDropDown")</div>
    <div class="col-lg-3">@Html.EditorFor(m => m.FullName)</div>
    <div class="col-lg-3">@Html.EditorFor(m => m.Email)</div>
</div>

<div class="row">
    <div class="col-md-6 text-left pb-15">
        <button type="button" class="btn btn-primary" id="btnFilter" onclick="refreshTable('#mainTable')" value="Филтриране" title="Филтриране">
            Филтриране
            <i class="fa fa-search" title="Търсене"></i>
        </button>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-right pb-15">
        <a asp-action="EpepUser_Add" class="btn btn-success">
            <i class="fa fa-plus"></i>
            Добави
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("EpepUser_ListData")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                        d.filter = {
                            EpepUserTypeId: $('#EpepUserTypeId').val(),
                            FullName: $('#FullName').val(),
                            Email: $('#Email').val()
                        }
                    }
                },
                filter:false,
                columns: [
                    {
                        name: 'userTypeName',
                        data: 'userTypeName',
                        title: 'Вид',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'fullName',
                        data: 'fullName',
                        title: 'Имена',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'lawyerNumber',
                        data: 'lawyerNumber',
                        title: 'Номер',
                        sortable: true,
                        searchable: true
                    }
                    ,{
                        name: 'email',
                        data: 'email',
                        title: 'Електронна поща',
                        sortable: true,
                        searchable: true
                    }
                    ,
                    {
                        name: 'actions',
                        data: "id",
                        title: "",
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (value) {
                            return TemplateToHtml('#templateEdit', value);
                        }
                    }
                ]
            });
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <a href="@Url.Action("EpepUser_Edit")/{{this}}" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
    </script>
}

IOWebApplication/Views/Epep/EpepUserAssignment_Edit.cshtml
@model EpepUserAssignment
@using  IOWebApplication.Infrastructure.Constants
@using IOWebApplication.Infrastructure.Data.Models.Common

@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Редакция на връзка към дело";
    }
    else
    {
        ViewData["Title"] = "Добавяне на връзка към дело";
    }
    bool canChange = (bool)ViewBag.canChange;
    string actionName = "EpepUserAssignment_Edit";
    if (!canChange)
    {
        actionName = "";
    }
}
@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="@actionName" method="post">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.EpepUserId)
            @Html.HiddenFor(x => x.DateFrom)

            <fieldset class="is-fieldset">
                <legend class="legend_1">Основни данни</legend>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div id="saveContainer">
                    <partial name="_SaveFormContent" model="@("#saveContainer")" />
                    @Html.EditorFor(x => x.CaseId, "SelectCase", new { onChange = "courtSelect();" })
                    @Html.EditorFor(x => x.CasePersonId, "GenericDropDown")
                    @Html.EditorFor(x => x.CanSummon)
                </div>

                <div class="form-group">
                    @if (canChange)
                    {
                        <input type="submit" value="Запис" class="btn btn-success single-click-submit" />
                    }
                    <a asp-action="EpepUser_Edit" asp-route-id="@Model.EpepUserId" class="btn btn-danger">Назад</a>

                    @if (Model.Id > 0)
                    {
                        <div class="pull-right">
                            @if (canChange)
                            {
                                @await Html.PartialAsync("_ExpiredInfoButton", new ExpiredInfoVM() { Id = Model.Id, DialogTitle = "Премахване на връзка към дело", ExpireSubmitUrl = Url.Action("Assigment_ExpiredInfo") })
                                <span>&nbsp;</span>
                            }
                            @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = Model.Id.ToString(), IconOnly = true })
                            <span>&nbsp;</span>
                            <partial name="MqInfo" model="@(new SourceTypeSelectVM() { SourceType = SourceTypeSelectVM.EpepUserAssignment, SourceId = Model.Id })" />
                        </div>
                    }
                </div>
            </fieldset>
        </form>
    </div>

</div>
@section scripts{
    <script>
        $(function () {
            $('#CaseId').parents('.case-container:first').data('court', @(Model.CourtId));
            initCase();
            courtSelect();
        });
        function courtSelect() {
            let caseId = $('#CaseId').val();
            requestCombo('@Url.Action("Get_CasePerson")', { caseId: caseId }, '#CasePersonId','@Model.CasePersonId');
        }
    </script>
}

IOWebApplication/Views/Epep/EpepUser_Edit.cshtml
@model EpepUser
@using  IOWebApplication.Infrastructure.Constants
@using IOWebApplication.Infrastructure.Models.ViewModels.Epep
@using IOWebApplication.Infrastructure.Data.Models.Common
@inject IOWebApplication.Infrastructure.Contracts.IUserContext userContext
@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Редакция на потребител в ЕПЕП";
    }
    else
    {
        ViewData["Title"] = "Добавяне на потребител в ЕПЕП";
    }
    var docInfo = (EpepDocumentInfoVM)ViewBag.documentInfo;
    var hasEpepUserOtherType = ViewBag.hasEpepUserOtherType == true;
}
@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="EpepUser_Edit" method="post">
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.DocumentId)
            @Html.HiddenFor(x => x.DocumentDecisionId)
            <fieldset class="is-fieldset">
                <legend class="legend_1">Основни данни</legend>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @if (docInfo != null)
                {
                    <div class="row">
                        <div class="col-lg-6">@Html.DisplayFor(x => docInfo.CourtName, "obj")</div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(x => docInfo.DocumentInfo)
                                <div>
                                    @if (userContext.CourtId == docInfo.CourtId)
                                    {
                                        <a href="@Url.Action("View","Document",new { id=docInfo.DocumentId})" target="_blank">
                                            @docInfo.DocumentInfo
                                        </a>
                                    }
                                    else
                                    {
                                        <span>@docInfo.DocumentInfo</span>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <div id="saveContainer">
                    <partial name="_SaveFormContent" model="@("#saveContainer")" />
                    <div class="row">
                        <div class="col-lg-6">
                            @if (Model.Id > 0)
                            {
                                @Html.HiddenFor(x => x.EpepUserTypeId)
                                @Html.DisplayFor(x => x.EpepUserTypeId, "objVal", new { value = ViewBag.epepUserType })
                            }
                            else
                            {
                                @Html.EditorFor(x => x.EpepUserTypeId, "GenericDropDown")
                            }
                        </div>
                        <div class="col-lg-6">@Html.EditorFor(x => x.BirthDate)</div>
                    </div>
                    <div id="lawyerControls">
                        <div class="row">
                            <div class="col-lg-12">@Html.EditorFor(x => x.LawyerLawUnitId, "LawUnit", null, new { lawUnitType = NomenclatureConstants.LawUnitTypes.Lawyer })</div>
                        </div>
                    </div>
                    <div id="personControls">
                        <div class="row">
                            <div class="col-lg-6">@Html.EditorFor(x => x.Uic)</div>
                            <div class="col-lg-6">@Html.EditorFor(x => x.FullName)</div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">@Html.EditorFor(x => x.Address)</div>
                        <div class="col-lg-6">@Html.EditorFor(x => x.Email)</div>
                    </div>
                    @Html.EditorFor(x => x.Description)
                </div>
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Запис" class="btn btn-success single-click-submit" />
                <a asp-action="EpepUser" class="btn btn-danger">Назад</a>

                @if (Model.Id > 0)
                {
                    <div class="pull-right">
                        @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = Model.Id.ToString(), IconOnly = true })
                        <span>&nbsp;</span>
                        <partial name="MqInfo" model="@(new SourceTypeSelectVM() { SourceType = SourceTypeSelectVM.EpepUser, SourceId = Model.Id })" />
                    </div>
                }
            </div>
        </form>
    </div>
    @if (Model.Id > 0)
    {
        <div class="col-md-6">
            <fieldset class="is-fieldset">
                <legend class="legend_1">Участие в дела</legend>
                <div class="pull-right">
                    <a asp-controller="Epep" asp-action="EpepUserAssignment_Add" asp-route-epepUserId="@Model.Id" class="btn btn-success btn-sm">
                        <i class="fa fa-plus"></i>
                        Добави
                    </a>
                </div>
                <table id="dtAssignments" class="table table-hover table-striped"></table>
            </fieldset>
        </div>
    }
</div>
@section scripts{
    <script>
        $(function () {
            $('#EpepUserTypeId').change(function () {
                switch ($(this).val()) {
                    case '@EpepConstants.UserTypes.Person':
                        $('#lawyerControls').hide();
                        $('#personControls').show();
                        break;
                    case '@EpepConstants.UserTypes.Lawyer':
                        $('#lawyerControls').show();
                        $('#personControls').hide();
                        break;
                    default:
                }
            }).trigger('change');
            @if(Model.Id > 0)
            {
                <text>loadAssignments();</text>
            }
            initLawUnit();
            @if (hasEpepUserOtherType) {
                <text>
            swalConfirm('Съществува създаден потребител от друг тип в ЕПЕП с тази електронна поща. Желаете ли да заредите съществуващите данни?', function () {
                document.location.href = '@Url.Action("EpepUser_AddFromEmail",new { email = Model.Email})';
                });
                </text>
            }
        });
        function loadAssignments() {
            $('#dtAssignments').DataTable({
                ajax: {
                    "url": "@Url.Action("EpepUserAssignment_ListData")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {
                        d.epepUserId = @(Model.Id);
                    }
                },
                filter:false,
                columns: [
                    {
                        name: 'courtName',
                        data: 'courtName',
                        title: 'Съд',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'caseInfo',
                        data: 'caseInfo',
                        title: 'Дело',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'sideInfo',
                        data: null,
                        title: 'Страна',
                        sortable: true,
                        searchable: true,
                        "render": function (a, b, item, c) {
                            return TemplateToHtml('#templateSide', item);
                        }
                    }
                    ,
                    {
                        name: 'actions',
                        data: null,
                        title: "",
                        sortable: false,
                        searchable: false,
                        className: "text-center noExport",
                        "render": function (a,b,item,c) {
                            return TemplateToHtml('#templateEdit', item);
                        }
                    }
                ]
            });
        }
    </script>
    <script id="templateSide" type="text/x-handlebars-template">
        {{sideInfo}}
        {{#if canSummon}}
        &nbsp;
        <i class="text-yellow fa fa-bell" title="Разрешено призоваване чрез ЕПЕП"></i>
        {{/if}}
    </script>
    <script id="templateEdit" type="text/x-handlebars-template">
        {{#if canChange}}
        <a href="@Url.Action("EpepUserAssignment_Edit")/{{id}}" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
        {{/if}}
    </script>
}

IOWebApplication/Views/Epep/Lawyers.cshtml
@{
    ViewData["Title"] = "Адвокати";
}
@section breadcrumb{
    @if (ViewBag.breadcrumbs != null)
    {
        <partial name="Breadcrumbs" model="@(List<IOWebApplication.Infrastructure.Models.ViewModels.Common.BreadcrumbsVM>)ViewBag.breadcrumbs" />
    }
}

<div class="row">
    <div class="col-md-12">
        <table id="mainTable" class="table table-hover table-striped"></table>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            var table = $('#mainTable').DataTable({
                ajax: {
                    "url": "@Url.Action("Lawyers_ListData")",
                    "type": "POST",
                    "datatype": "json",
                    data: function (d) {

                    }
                },
                columns: [
                    {
                        name: 'name',
                        data: 'name',
                        title: 'Имена',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'number',
                        data: 'number',
                        title: 'Номер',
                        sortable: true,
                        searchable: true
                    },
                    {
                        name: 'college',
                        data: 'college',
                        title: 'Колегия',
                        sortable: true,
                        searchable: true
                    }
                    //,
                    //{
                    //    name: 'actions',
                    //    data: "id",
                    //    title: "",
                    //    sortable: false,
                    //    searchable: false,
                    //    className: "text-center noExport",
                    //    "render": function (value) {
                    //        return TemplateToHtml('#templateEdit', value);
                    //    }
                    //}
                ]
            });
        });
    </script>

    <script id="templateEdit" type="text/x-handlebars-template">
        <a onclick="EditHtmlTemplate({{this}})" class="btn btn-warning btn-sm" title="Редакция"><i class="fa fa-edit"></i><span class="hidden-sm hidden-xs"></span></a>
        <a onclick="IndexLinkHtmlTemplate({{this}})" class="btn btn-dropbox btn-sm" title="Връзки по вид съд/дело"><i class="fa fa-external-link"></i><span class="hidden-sm hidden-xs"></span></a>
        <a onclick="IndexParamHtmlTemplate({{this}})" class="btn btn-google btn-sm" title="Параметри в бланка"><i class="fa fa-paragraph"></i><span class="hidden-sm hidden-xs"></span></a>
        <a href="@Url.Action("Preview")/{{this}}" class="btn btn-file btn-sm" title="Преглед на бланка"><i class="fa fa-file-o"></i><span class="hidden-sm hidden-xs"> Преглед TinyMCE</span></a>
        <a onclick="printTemplateRaw({{this}})" class="btn btn-file btn-sm" title="Преглед на бланка"><i class="fa fa-file-o"></i><span class="hidden-sm hidden-xs"> Преглед Html</span></a>
        <a href="@Url.Action("HtmlTemplate_GetNotSetParam")/{{this}}" class="btn btn-file btn-sm" title="Непопълнени параметри"><i class="fa fa-paragraph"></i><span class="hidden-sm hidden-xs"></span></a>
        @*<a href="@Url.Action("DownloadFile")/{{this}}" class="btn btn-file btn-sm" title="Сваляне"><i class="fa fa-save"></i><span class="hidden-sm hidden-xs"> Сваляне</span></a>*@
    </script>
}

IOWebApplication/Views/Epep/ManageData.cshtml
@model EpepManageDataVM
@using  IOWebApplication.Infrastructure.Constants
@using IOWebApplication.Infrastructure.Models.ViewModels.Epep

@{
    ViewData["Title"] = "Корекция на данни в ЕПЕП";
}
<div class="row">
    <div class="col-md-6">
        <form asp-action="ManageData" method="post">


            <fieldset class="is-fieldset">
                <legend class="legend_1">Основни данни</legend>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div id="saveContainer">
                    <partial name="_SaveFormContent" model="@("#saveContainer")" />
                    <div class="row">
                        <div class="col-lg-12">
                            <h4 class="text-warning">@Model.ResponseMessage</h4>
                        </div>
                    </div>

                    @Html.EditorFor(x => x.DataType, "GenericDropDown")
                    @Html.EditorFor(x => x.ObjectId)
                    @Html.EditorFor(x => x.SecurityCode, "Password")
                </div>
            </fieldset>
            <div class="form-group">
                <input type="submit" value="Премахване" class="btn btn-danger btn-md" />
                <div class="pull-right">
                    @await Html.PartialAsync("_ShowLogOperation", new IOWebApplication.Core.Models.ShowLogModel() { ObjectKey = "1" })
                </div>
            </div>

        </form>
    </div>

</div>